# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-13 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('releaseDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisherName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('dateFounded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='systemRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoryNeeded', models.CharField(max_length=100)),
                ('miniumumDiskSpace', models.CharField(max_length=100)),
                ('gpuRequired', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='publisherName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignment2.publisher'),
        ),
        migrations.AddField(
            model_name='game',
            name='systemRequirements',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='assignment2.systemRequirements'),
        ),
    ]
