# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-12 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('releaseDate', models.DateField()),
                ('publisherName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisherName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('dateFounded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='systemRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=100)),
                ('memoryNeeded', models.CharField(max_length=100)),
                ('miniumumDiskSpace', models.CharField(max_length=100)),
                ('gpuRequired', models.CharField(max_length=50)),
            ],
        ),
    ]
