# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-13 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='publisherName',
            new_name='publisher',
        ),
    ]
