# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0002_auto_20180513_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='systemRequirements',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignment2.systemRequirements'),
        ),
    ]
