# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0004_auto_20180515_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignment2.publisher'),
        ),
        migrations.AlterField(
            model_name='game',
            name='systemRequirements',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignment2.systemRequirements'),
        ),
    ]
